# Generated by Django 3.1.2 on 2021-01-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210127_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organise',
            new_name='is_organiser',
        ),
    ]
